### PR TITLE
Milestone: Friendships v2

### PR DESCRIPTION
**Pull request by gscarv13**
This pull request contains the following:

- Optimized queries to solve the N+1 problem
- When confirmed, the friendship will have 2 rows on the database

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there 😊
Great work you done making all the requirements of this milestone. You have set up the confirmation of a "Friend", pending, and inverted correct. Well done ✔
RSpec tests ✔
However, there are still a few more changes to do in order to get the approval 🙏😊

<hr>

- [x] There's room to improve the timeline posts method in your posts controller. When it's in pending mode, the User who sent the friendship request can see the posts of the "Sent_to" user. Kindly modify this issue.
- **OPTIONAL** It's better if you move the timeline_posts method from the posts controller to the User model or the helpers. Please keep in mind that controllers are used only for passing the user's data safely (Using the private keyword for the private methods such as post_params and user_params) and for the user's requests (The RESTful methods index, show, new, etc).

<hr>

Kindly make the required changes, then submit another CRR.
Good luck and happy coding 👨‍💻💻

<hr>

Please feel free to contact me on Slack with the name "Mahmoud Bakr" if had any questions 🤗

**Comment by gscarv13** [comment]
## Thanks for your review @MahmoudBakr23 !

The following changes has been made:

- Updated the friends list query to show only approved friendships
- Moved timeline_posts method into a scope

**Review by enaburekhan — APPROVED** [review]
# Status: Approve:heavy_check_mark:
**Hi Silva!
Congratulations. The App is working as expected.
 Move on with the next milestone:walking:.**

**Optional**
- [x] Move the logic in application.html.erb under layout in view to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) if you need help on how to use a helper in rails. See [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright. I will encourage you to fix this before merging the PR.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by gscarv13** [comment]
## Thanks for your review @enaburekhan !

The following changes has been made:

- Removed the logic from `application.html.erb` view
- Created flash helpers
- Added navigation bar partial

**Pull request merged**
